using System;
using System.IO;
using System.Linq;
using System.Text;

using AwesomeAssertions;

using libbgcode.NET;

using Homespool.Host.PrintFiles.GCode;

namespace Homespool.Host.Test;

/// <summary>
/// Finding the PNG preview in a print file, in both containers a printer accepts.
/// </summary>
/// <remarks>
/// The files are assembled here in the shape PrusaSlicer writes - three QOI previews for the printer's
/// screens and one PNG - rather than kept as fixtures: a real preview is tens of kilobytes of somebody's
/// model, and every question these tests ask is about which image is picked, not what it shows.
/// </remarks>
public class GCodeThumbnailReaderTests
{
    /// <summary>A real 1x1 PNG.</summary>
    private static readonly byte[] TinyPng = Convert.FromBase64String(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==");

    /// <summary>
    /// The binary layout a current profile produces: the printer's QOI previews and one PNG. The PNG
    /// is what comes back, byte for byte.
    /// </summary>
    [Fact]
    public void FindsThePngAmongABinaryFilesPreviews()
    {
        byte[] png = Png(1);

        byte[]? image = Read(Binary(
            (new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Qoi, 16, 16), Qoi()),
            (new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Qoi, 313, 173), Qoi()),
            (new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Qoi, 480, 240), Qoi()),
            (new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Png, 380, 285), png)));

        image.Should().Equal(png);
    }

    /// <summary>
    /// Two PNGs: the larger wins, wherever it sits. The smaller comes second here, so taking the last
    /// or the first would both fail one of the two orders.
    /// </summary>
    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void TakesTheLargerOfTwoBinaryPngs(bool largerFirst)
    {
        byte[] small = Png(1);
        byte[] large = Png(2);
        (BgcodeThumbnailParameters, byte[]) smallBlock = (new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Png, 160, 120), small);
        (BgcodeThumbnailParameters, byte[]) largeBlock = (new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Png, 380, 285), large);

        byte[]? image = Read(largerFirst ? Binary(largeBlock, smallBlock) : Binary(smallBlock, largeBlock));

        image.Should().Equal(large);
    }

    /// <summary>
    /// Previews only in formats a browser cannot show: none, rather than a QOI served as a PNG.
    /// </summary>
    [Fact]
    public void ABinaryFileWithOnlyQoiPreviewsHasNone()
    {
        Read(Binary((new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Qoi, 313, 173), Qoi()))).Should().BeNull();
    }

    /// <summary>
    /// A block declared PNG whose bytes are not one. The response says image/png, so the reader checks
    /// before anything is served under that type.
    /// </summary>
    [Fact]
    public void ABinaryPreviewThatIsNotReallyAPngIsRefused()
    {
        byte[] html = Encoding.ASCII.GetBytes("<script>alert(1)</script>");

        Read(Binary((new BgcodeThumbnailParameters(BgcodeThumbnailFormat.Png, 380, 285), html))).Should().BeNull();
    }

    /// <summary>
    /// The plain layout: the same four previews as base64 comments ahead of the first command. The QOI
    /// sections are tagged as such and stepped over.
    /// </summary>
    [Fact]
    public void FindsThePngAmongAPlainFilesPreviews()
    {
        byte[] png = Png(1);

        string gcode = "; generated by PrusaSlicer 2.9.6 on 2026-07-27 at 20:03:14 UTC\n\n" +
                       Section("thumbnail_QOI", "16x16", Qoi()) +
                       Section("thumbnail_QOI", "313x173", Qoi()) +
                       Section("thumbnail_QOI", "480x240", Qoi()) +
                       Section("thumbnail", "380x285", png) +
                       "; external perimeters extrusion width = 0.45mm\n\n" +
                       "M73 P0 R164\nG28 ; home\n";

        Read(Encoding.ASCII.GetBytes(gcode)).Should().Equal(png);
    }

    /// <summary>
    /// Two PNG sections: the larger wins in either order, as in the binary container.
    /// </summary>
    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void TakesTheLargerOfTwoPlainPngs(bool largerFirst)
    {
        byte[] large = Png(2);
        string largeSection = Section("thumbnail", "380x285", large);
        string smallSection = Section("thumbnail", "160x120", Png(1));

        string gcode = (largerFirst ? largeSection + smallSection : smallSection + largeSection) + "G28\n";

        Read(Encoding.ASCII.GetBytes(gcode)).Should().Equal(large);
    }

    /// <summary>
    /// The first command ends the header. A section after it is not a preview a slicer wrote, and
    /// reading on for one would read the whole of a large file.
    /// </summary>
    [Fact]
    public void APlainFileStopsLookingAtItsFirstCommand()
    {
        string gcode = "; generated by PrusaSlicer\nG28\n" + Section("thumbnail", "380x285", Png(1));

        Read(Encoding.ASCII.GetBytes(gcode)).Should().BeNull();
    }

    /// <summary>
    /// A section that never ends yields nothing rather than whatever had been collected.
    /// </summary>
    [Fact]
    public void AnUnfinishedPlainSectionIsNotAPreview()
    {
        string section = Section("thumbnail", "380x285", Png(1));
        string unfinished = section[..section.IndexOf("; thumbnail end", StringComparison.Ordinal)];

        Read(Encoding.ASCII.GetBytes(unfinished + "G28\n")).Should().BeNull();
    }

    /// <summary>
    /// The existing fixtures are real slicer output with no previews at all, in both containers - and
    /// a file named <c>.gcode</c> that is binary inside, which the magic decides rather than the name.
    /// </summary>
    [Theory]
    [InlineData("metadata-coreone-hf04-pla.bgcode")]
    [InlineData("metadata-mk35-04-pla.gcode")]
    [InlineData("metadata-mk35-binary-named-gcode.gcode")]
    public void ARealFileWithoutPreviewsHasNone(string fixture)
    {
        GCodeThumbnailReader.ReadFile(Path.Combine(AppContext.BaseDirectory, fixture)).Should().BeNull();
    }

    /// <summary>
    /// A file of one line with no newline is read no further than its head. A line reader builds the
    /// whole line before it can be told to stop, and anybody who may print can upload such a file and
    /// start it: 64 MiB of it once cost 640 MiB, read on every poll of the printer's page.
    /// </summary>
    [Fact]
    public void AFileOfOneEndlessLineIsReadNoFurtherThanItsHead()
    {
        byte[] file = new byte[64 * 1024 * 1024];
        Array.Fill(file, (byte)';');

        using MemoryStream stream = new(file);
        long before = GC.GetAllocatedBytesForCurrentThread();

        byte[]? image = GCodeThumbnailReader.Read(stream);

        long allocated = GC.GetAllocatedBytesForCurrentThread() - before;

        image.Should().BeNull();
        allocated.Should().BeLessThan(8L * GCodeThumbnailReader.MaxHeadBytes, "reading is bounded by the head, not the file");
    }

    /// <summary>
    /// A preview whose section runs past the head is not found: the file shows none, rather than the
    /// reader following it.
    /// </summary>
    [Fact]
    public void APreviewRunningPastTheHeadIsNotFound()
    {
        byte[] large = [.. TinyPng, .. new byte[GCodeThumbnailReader.MaxHeadBytes]];

        string gcode = Section("thumbnail", "1024x1024", large) + "G28\n";

        Read(Encoding.ASCII.GetBytes(gcode)).Should().BeNull();
    }

    /// <summary>A file that is not there is no preview, not an exception.</summary>
    [Fact]
    public void AMissingFileHasNone()
    {
        GCodeThumbnailReader.ReadFile(Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N") + ".bgcode"))
                            .Should().BeNull();
    }

    private static byte[]? Read(byte[] file)
    {
        using MemoryStream stream = new(file);

        return GCodeThumbnailReader.Read(stream);
    }

    /// <summary>A PNG that can be told apart from another: PNG readers ignore bytes after the end.</summary>
    private static byte[] Png(byte tag)
    {
        return [.. TinyPng, tag];
    }

    /// <summary>Stands in for a QOI image; only its tag and header decide anything here.</summary>
    private static byte[] Qoi()
    {
        return [.. "qoif"u8, 0, 0, 0, 1, 0, 0, 0, 1, 4, 0];
    }

    private static byte[] Binary(params (BgcodeThumbnailParameters parameters, byte[] image)[] thumbnails)
    {
        using MemoryStream output = new();

        using (BgcodeWriter writer = new(output, leaveOpen: true))
        {
            writer.WriteFileMetadata("Producer=test\n");
            writer.WritePrinterMetadata("printer_model=COREONE\n");

            foreach ((BgcodeThumbnailParameters parameters, byte[] image) in thumbnails)
            {
                writer.WriteThumbnail(parameters, image, BgcodeCompression.None);
            }

            writer.WritePrintMetadata("filament used [g]=0.08\n");
            writer.WriteSlicerMetadata("; printer_model = COREONE\n");
            writer.WriteGCode("G28 ; home\n");
        }

        return output.ToArray();
    }

    /// <summary>A preview as PrusaSlicer writes it into a plain file: base64 in 78-character comment lines.</summary>
    private static string Section(string tag, string size, byte[] image)
    {
        string encoded = Convert.ToBase64String(image);
        StringBuilder text = new();

        text.Append("; ").Append(tag).Append(" begin ").Append(size).Append(' ').Append(encoded.Length).Append('\n');

        foreach (char[] line in encoded.Chunk(78))
        {
            text.Append("; ").Append(line).Append('\n');
        }

        text.Append("; ").Append(tag).Append(" end\n;\n\n");

        return text.ToString();
    }
}
