; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 15:00:48 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.40mm
; first layer extrusion width = 0.50mm

M73 P0 R0
M73 Q0 S0
M201 X4000 Y4000 Z200 E2500 ; sets maximum accelerations, mm/sec^2
M203 X300 Y300 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P4000 R1250 T4000 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E5.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

M486 S0
M486 Acube.stl
M486 S-1

;TYPE:Custom
M17 ; enable steppers
M862.1 P0.4 A0 F0 ; nozzle check
M862.3 P "MK3.5" ; printer model check
M862.5 P2 ; g-code level check
M862.6 P"Input shaper" ; FW feature check
M115 U6.5.7+12836

M555 X123.5 Y99.5 W32 H7

G90 ; use absolute coordinates
M83 ; extruder relative mode

M140 S60 ; set bed temp
M104 T0 S170 ; set extruder temp for bed leveling
M109 T0 R170 ; wait for temp
M190 S60 ; wait for bed temp

G28 ; home all

G29 P1 ; invalidate mbl & probe print area
G29 P1 X23 Y5 W80 H20 C ; probe near purge place
G29 P3.2 ; interpolate mbl probes
G29 P3.13 ; extrapolate mbl outside probe area
G29 A ; activate mbl

; prepare for purge
M104 S230
G0 X0 Y-4 Z15 F4800 ; move away and ready for the purge
M109 S230

; Extrude purge line

G92 E0 ; reset extruder position
G0 E7 X15 Z0.2 F500 ; purge
M73 P2 R0
M73 Q2 S0
G0 X25 E4 F500 ; purge
M73 P8 R0
M73 Q8 S0
G0 X35 E4 F650 ; purge
M73 P10 R0
M73 Q10 S0
G0 X45 E4 F800 ; purge
M73 P12 R0
M73 Q12 S0
G0 X48 Z0.05 F8000 ; wipe, move close to the bed
M73 P14 R0
M73 Q14 S0
G0 X51 Z0.2 F8000 ; wipe, move quickly away from the bed

G92 E0
M221 S100 ; reset flow to 100%
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion





M572 S0.035 ; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-.8 F2100
G1 Z.4 F720
M486 S0
G1 X125.793 Y105.793 F18000
G1 Z.2 F720
M73 P15 R0
M73 Q16 S0
G1 E.8 F2100
M204 P500
;TYPE:Perimeter
;WIDTH:0.499999
G1 F900
G1 X124.207 Y105.793 E.06028
G1 X124.207 Y104.207 E.06028
M73 P16 R0
G1 X125.793 Y104.207 E.06028
G1 X125.793 Y105.733 E.058
M73 Q17 S0
M204 P2500
M204 T250
G1 X126.25 Y106.25 F18000
M204 T4000
M204 P500
;TYPE:External perimeter
G1 F900
G1 X123.75 Y106.25 E.09502
G1 X123.75 Y103.75 E.09502
M73 P17 R0
G1 X126.25 Y103.75 E.09502
M73 Q18 S0
G1 X126.25 Y106.19 E.09274
M73 P18 R0
M204 P2500
;WIPE_START
G1 F14400
G1 X126.25 Y106.25 E-.00831
G1 X123.75 Y106.25 E-.34635
G1 X123.75 Y103.75 E-.34635
G1 X124.465 Y103.75 E-.09899
M73 Q19 S0
;WIPE_END
G1 Z.4 F720
G1 X124.492 Y104.39 F18000
G1 Z.2 F720
G1 E.8 F2100
M204 P500
;TYPE:Solid infill
;WIDTH:0.591415
G1 F900
M73 P19 R0
G1 X125.404 Y105.302 E.05882
G1 X125.404 Y105.404 E.00465
G1 X124.731 Y105.404 E.03069
G1 X124.39 Y105.063 E.02199
M204 P2500
M106 S84.15
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4
M201 X4000 Y4000

;WIPE_START
G1 F14400
G1 X124.731 Y105.404 E-.06681
G1 X125.404 Y105.404 E-.09324
G1 X125.404 Y105.302 E-.01413
G1 X124.492 Y104.39 E-.17869
;WIPE_END
G1 E-.44713 F2100
M73 Q20 S0
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.4
M74 W0.00218558

M104 S225 ; set temperature
G1 Z.6
G1 X125.868 Y105.868 F18000
G1 Z.4 F720
G1 E.8 F2100
M73 P20 R0
M204 P3000
;TYPE:Perimeter
;WIDTH:0.449999
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
G1 X125.868 Y104.132 E.05876
M73 Q21 S0
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 P21 R0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
G1 X126.275 Y103.725 E.08631
M73 Q22 S0
G1 X126.275 Y106.215 E.08428
M73 P22 R0
M204 P2500
;WIPE_START
G1 F14400
M73 Q23 S0
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z.6 F720
M73 P23 R0
G1 X124.841 Y105.044 F18000
G1 Z.4 F720
G1 E.8 F2100
M204 P3000
;TYPE:Solid infill
;WIDTH:0.361285
G1 F900
G1 X124.841 Y105.159 E.00304
G1 X125.159 Y105.159 E.00842
G1 X125.159 Y104.841 E.00842
G1 X124.841 Y104.841 E.00842
;WIDTH:0.405642
G1 X124.659 Y104.761 E.006
;WIDTH:0.449999
G1 X124.478 Y104.682 E.00668
G1 X124.478 Y105.522 E.02843
G1 X125.522 Y105.522 E.03534
M73 Q24 S0
G1 X125.522 Y104.478 E.03534
G1 X124.478 Y104.478 E.03534
M204 P2500
M106 S170.85
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.6
M201 X4000 Y4000

;WIPE_START
G1 F14400
M73 P24 R0
G1 X125.522 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.14464
G1 X124.478 Y105.522 E-.14464
G1 X124.478 Y104.682 E-.11638
G1 X124.659 Y104.761 E-.02736
G1 X124.841 Y104.841 E-.02754
G1 X125.159 Y104.841 E-.04406
G1 X125.159 Y105.159 E-.04406
G1 X124.841 Y105.159 E-.04406
G1 X124.841 Y105.044 E-.01593
;WIPE_END
G1 E-.04669 F2100
G1 Z.6 F720
;AFTER_LAYER_CHANGE
;0.6
M74 W0.00442742

G1 X125.868 Y105.868 F18000
M73 Q25 S0
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
M73 P25 R0
G1 X125.868 Y104.132 E.05876
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 Q26 S0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
M73 P26 R0
G1 X126.275 Y103.725 E.08631
M73 Q27 S0
G1 X126.275 Y106.215 E.08428
M73 P27 R0
M204 P2500
;WIPE_START
G1 F14400
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z.8 F720
M73 Q28 S0
G1 X125.044 Y105.159 F18000
G1 Z.6 F720
G1 E.8 F2100
M204 P3000
;TYPE:Solid infill
;WIDTH:0.361285
G1 F900
M73 P28 R0
G1 X125.159 Y105.159 E.00304
G1 X125.159 Y104.841 E.00842
G1 X124.841 Y104.841 E.00842
G1 X124.841 Y105.159 E.00842
;WIDTH:0.405642
G1 X124.761 Y105.341 E.006
;WIDTH:0.449999
G1 X124.682 Y105.522 E.00668
G1 X125.522 Y105.522 E.02843
G1 X125.522 Y104.478 E.03534
G1 X124.478 Y104.478 E.03534
G1 X124.478 Y105.522 E.03534
M73 Q29 S0
M204 P2500
M106 S255
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8
M201 X3999.99 Y3999.99

;WIPE_START
G1 F14400
G1 X124.478 Y104.478 E-.14464
G1 X125.522 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.14464
G1 X124.682 Y105.522 E-.11638
M73 P29 R0
G1 X124.761 Y105.341 E-.02736
G1 X124.841 Y105.159 E-.02754
G1 X124.841 Y104.841 E-.04406
G1 X125.159 Y104.841 E-.04406
G1 X125.159 Y105.159 E-.04406
G1 X125.044 Y105.159 E-.01593
;WIPE_END
G1 E-.04669 F2100
G1 Z.8 F720
;AFTER_LAYER_CHANGE
;0.8
M74 W0.00666925

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
M73 Q30 S0
G1 X125.868 Y104.132 E.05876
M73 P30 R0
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
M73 P31 R0
M73 Q31 S0
G1 X126.275 Y103.725 E.08631
G1 X126.275 Y106.215 E.08428
M73 Q32 S0
M204 P2500
;WIPE_START
G1 F14400
M73 P32 R0
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z1 F720
G1 X124.682 Y105.522 F18000
G1 Z.8 F720
G1 E.8 F2100
M204 P4000
;TYPE:Internal infill
;WIDTH:0.45
G1 F900
M73 Q33 S0
G1 X125.522 Y105.522 E.02843
G1 X124.478 Y104.478 E.04998
G1 X125.522 Y104.478 E.03534
M73 P33 R0
G1 X124.478 Y105.522 E.04998
G1 X124.478 Y104.682 E.02843
M204 P2500
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1
M201 X3999.99 Y3999.99

;WIPE_START
G1 F14400
G1 X124.478 Y105.522 E-.11638
G1 X125.522 Y104.478 E-.20455
G1 X124.478 Y104.478 E-.14464
M73 Q34 S0
G1 X125.522 Y105.522 E-.20455
G1 X124.682 Y105.522 E-.11638
;WIPE_END
G1 E-.0135 F2100
G1 Z1 F720
;AFTER_LAYER_CHANGE
;1
M74 W0.00896098

G1 X125.868 Y105.868 F18000
M73 P34 R0
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
;WIDTH:0.449999
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
G1 X125.868 Y104.132 E.05876
M73 Q35 S0
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 P35 R0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
G1 X126.275 Y103.725 E.08631
M73 P36 R0
M73 Q36 S0
G1 X126.275 Y106.215 E.08428
M204 P2500
;WIPE_START
G1 F14400
M73 Q37 S0
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
M73 P37 R0
;WIPE_END
G1 Z1.2 F720
G1 X124.682 Y105.522 F18000
G1 Z1 F720
G1 E.8 F2100
M204 P4000
;TYPE:Internal infill
;WIDTH:0.45
G1 F900
G1 X125.522 Y105.522 E.02843
G1 X124.478 Y104.478 E.04998
G1 X125.522 Y104.478 E.03534
M73 Q38 S0
G1 X124.478 Y105.522 E.04998
G1 X124.478 Y104.682 E.02843
M73 P38 R0
M204 P2500
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.2
M201 X3999.99 Y3999.99

;WIPE_START
G1 F14400
G1 X124.478 Y105.522 E-.11638
G1 X125.522 Y104.478 E-.20455
G1 X124.478 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.20455
G1 X124.682 Y105.522 E-.11638
;WIPE_END
G1 E-.0135 F2100
G1 Z1.2 F720
;AFTER_LAYER_CHANGE
;1.2
M74 W0.0112527

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M73 Q39 S0
M204 P3000
;TYPE:Perimeter
;WIDTH:0.449999
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
M73 P39 R0
G1 X125.868 Y104.132 E.05876
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 Q40 S0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
M73 P40 R0
G1 X126.275 Y103.725 E.08631
G1 X126.275 Y106.215 E.08428
M73 P41 R0
M73 Q41 S0
M204 P2500
;WIPE_START
G1 F14400
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z1.4 F720
M73 Q42 S0
G1 X124.682 Y105.522 F18000
G1 Z1.2 F720
G1 E.8 F2100
M204 P4000
;TYPE:Internal infill
;WIDTH:0.45
G1 F900
M73 P42 R0
G1 X125.522 Y105.522 E.02843
G1 X124.478 Y104.478 E.04998
G1 X125.522 Y104.478 E.03534
G1 X124.478 Y105.522 E.04998
G1 X124.478 Y104.682 E.02843
M73 Q43 S0
M204 P2500
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.4
M201 X3999.99 Y3999.99

;WIPE_START
G1 F14400
G1 X124.478 Y105.522 E-.11638
G1 X125.522 Y104.478 E-.20455
G1 X124.478 Y104.478 E-.14464
M73 P43 R0
G1 X125.522 Y105.522 E-.20455
G1 X124.682 Y105.522 E-.11638
;WIPE_END
G1 E-.0135 F2100
G1 Z1.4 F720
;AFTER_LAYER_CHANGE
;1.4
M74 W0.0135444

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
;WIDTH:0.449999
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
M73 Q44 S0
G1 X125.868 Y104.132 E.05876
M73 P44 R0
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
M73 Q45 S0
G1 X126.275 Y103.725 E.08631
M73 P45 R0
G1 X126.275 Y106.215 E.08428
M204 P2500
;WIPE_START
G1 F14400
M73 P46 R0
M73 Q46 S0
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z1.6 F720
G1 X124.682 Y105.522 F18000
G1 Z1.4 F720
G1 E.8 F2100
M204 P4000
;TYPE:Internal infill
;WIDTH:0.45
G1 F900
M73 Q47 S0
G1 X125.522 Y105.522 E.02843
G1 X124.478 Y104.478 E.04998
G1 X125.522 Y104.478 E.03534
M73 P47 R0
G1 X124.478 Y105.522 E.04998
G1 X124.478 Y104.682 E.02843
M204 P2500
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.6
M201 X3999.98 Y3999.98

;WIPE_START
G1 F14400
G1 X124.478 Y105.522 E-.11638
G1 X125.522 Y104.478 E-.20455
G1 X124.478 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.20455
M73 Q48 S0
G1 X124.682 Y105.522 E-.11638
;WIPE_END
G1 E-.0135 F2100
G1 Z1.6 F720
;AFTER_LAYER_CHANGE
;1.6
M74 W0.0158362

G1 X125.868 Y105.868 F18000
M73 P48 R0
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
;WIDTH:0.449999
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
G1 X125.868 Y104.132 E.05876
G1 X125.868 Y105.808 E.05673
M73 Q49 S0
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 P49 R0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
G1 X126.275 Y103.725 E.08631
M73 P50 R0
M73 Q50 S0
G1 X126.275 Y106.215 E.08428
M204 P2500
;WIPE_START
G1 F14400
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
M73 Q51 S0
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z1.8 F720
M73 P51 R0
G1 X124.682 Y105.522 F18000
G1 Z1.6 F720
G1 E.8 F2100
M204 P4000
;TYPE:Internal infill
;WIDTH:0.45
G1 F900
G1 X125.522 Y105.522 E.02843
G1 X124.478 Y104.478 E.04998
G1 X125.522 Y104.478 E.03534
G1 X124.478 Y105.522 E.04998
M73 Q52 S0
G1 X124.478 Y104.682 E.02843
M73 P52 R0
M204 P2500
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.8
M201 X3999.98 Y3999.98

;WIPE_START
G1 F14400
G1 X124.478 Y105.522 E-.11638
G1 X125.522 Y104.478 E-.20455
G1 X124.478 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.20455
G1 X124.682 Y105.522 E-.11638
;WIPE_END
G1 E-.0135 F2100
G1 Z1.8 F720
;AFTER_LAYER_CHANGE
;1.8
M74 W0.0181279

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M73 Q53 S0
M204 P3000
;TYPE:Perimeter
;WIDTH:0.449999
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
M73 P53 R0
G1 X125.868 Y104.132 E.05876
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 Q54 S0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
M73 P54 R0
G1 X126.275 Y103.725 E.08631
G1 X126.275 Y106.215 E.08428
M73 P55 R0
M73 Q55 S0
M204 P2500
;WIPE_START
G1 F14400
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z2 F720
G1 X124.682 Y105.522 F18000
M73 Q56 S0
G1 Z1.8 F720
G1 E.8 F2100
M204 P4000
;TYPE:Internal infill
;WIDTH:0.45
G1 F900
M73 P56 R0
G1 X125.522 Y105.522 E.02843
G1 X124.478 Y104.478 E.04998
G1 X125.522 Y104.478 E.03534
G1 X124.478 Y105.522 E.04998
G1 X124.478 Y104.682 E.02843
M204 P2500
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2
M201 X3999.98 Y3999.98

;WIPE_START
G1 F14400
M73 Q57 S0
G1 X124.478 Y105.522 E-.11638
G1 X125.522 Y104.478 E-.20455
G1 X124.478 Y104.478 E-.14464
M73 P57 R0
G1 X125.522 Y105.522 E-.20455
G1 X124.682 Y105.522 E-.11638
;WIPE_END
G1 E-.0135 F2100
G1 Z2 F720
;AFTER_LAYER_CHANGE
;2
M74 W0.0204196

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
;WIDTH:0.449999
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
G1 X125.868 Y104.132 E.05876
M73 Q58 S0
G1 X125.868 Y105.808 E.05673
M73 P58 R0
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
M73 Q59 S0
G1 X126.275 Y103.725 E.08631
M73 P59 R0
G1 X126.275 Y106.215 E.08428
M204 P2500
;WIPE_START
G1 F14400
M73 P60 R0
M73 Q60 S0
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z2.2 F720
G1 X124.682 Y105.522 F18000
G1 Z2 F720
G1 E.8 F2100
M204 P4000
;TYPE:Internal infill
;WIDTH:0.45
G1 F900
G1 X125.522 Y105.522 E.02843
G1 X124.478 Y104.478 E.04998
M73 Q61 S0
G1 X125.522 Y104.478 E.03534
M73 P61 R0
G1 X124.478 Y105.522 E.04998
G1 X124.478 Y104.682 E.02843
M204 P2500
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.2
M201 X3999.98 Y3999.98

;WIPE_START
G1 F14400
G1 X124.478 Y105.522 E-.11638
G1 X125.522 Y104.478 E-.20455
G1 X124.478 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.20455
G1 X124.682 Y105.522 E-.11638
M73 Q62 S0
;WIPE_END
G1 E-.0135 F2100
G1 Z2.2 F720
;AFTER_LAYER_CHANGE
;2.2
M74 W0.0227114

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M73 P62 R0
M204 P3000
;TYPE:Perimeter
;WIDTH:0.449999
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
G1 X125.868 Y104.132 E.05876
G1 X125.868 Y105.808 E.05673
M73 Q63 S0
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 P63 R0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
G1 X126.275 Y103.725 E.08631
M73 Q64 S0
G1 X126.275 Y106.215 E.08428
M73 P64 R0
M204 P2500
;WIPE_START
G1 F14400
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
M73 Q65 S0
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z2.4 F720
M73 P65 R0
G1 X125.044 Y105.159 F18000
G1 Z2.2 F720
G1 E.8 F2100
M204 P3000
;TYPE:Solid infill
;WIDTH:0.361285
G1 F900
G1 X125.159 Y105.159 E.00304
G1 X125.159 Y104.841 E.00842
G1 X124.841 Y104.841 E.00842
G1 X124.841 Y105.159 E.00842
;WIDTH:0.405642
G1 X124.761 Y105.341 E.006
;WIDTH:0.449999
G1 X124.682 Y105.522 E.00668
G1 X125.522 Y105.522 E.02843
G1 X125.522 Y104.478 E.03534
G1 X124.478 Y104.478 E.03534
M73 Q66 S0
G1 X124.478 Y105.522 E.03534
M204 P2500
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.4
M201 X3999.97 Y3999.97

;WIPE_START
G1 F14400
M73 P66 R0
G1 X124.478 Y104.478 E-.14464
G1 X125.522 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.14464
G1 X124.682 Y105.522 E-.11638
G1 X124.761 Y105.341 E-.02736
G1 X124.841 Y105.159 E-.02754
G1 X124.841 Y104.841 E-.04406
G1 X125.159 Y104.841 E-.04406
G1 X125.159 Y105.159 E-.04406
G1 X125.044 Y105.159 E-.01593
;WIPE_END
G1 E-.04669 F2100
G1 Z2.4 F720
;AFTER_LAYER_CHANGE
;2.4
M74 W0.0249532

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
G1 F900
M73 Q67 S0
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
M73 P67 R0
G1 X125.868 Y104.132 E.05876
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 Q68 S0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
M73 P68 R0
G1 X126.275 Y103.725 E.08631
G1 X126.275 Y106.215 E.08428
M73 P69 R0
M73 Q69 S0
M204 P2500
;WIPE_START
G1 F14400
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z2.6 F720
G1 X124.841 Y105.044 F18000
G1 Z2.4 F720
M73 Q70 S0
G1 E.8 F2100
M204 P3000
;TYPE:Solid infill
;WIDTH:0.361285
G1 F900
M73 P70 R0
G1 X124.841 Y105.159 E.00304
G1 X125.159 Y105.159 E.00842
G1 X125.159 Y104.841 E.00842
G1 X124.841 Y104.841 E.00842
;WIDTH:0.405642
G1 X124.659 Y104.761 E.006
;WIDTH:0.449999
G1 X124.478 Y104.682 E.00668
G1 X124.478 Y105.522 E.02843
G1 X125.522 Y105.522 E.03534
G1 X125.522 Y104.478 E.03534
G1 X124.478 Y104.478 E.03534
M204 P2500
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.6
M201 X3999.97 Y3999.97

;WIPE_START
G1 F14400
M73 Q71 S0
G1 X125.522 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.14464
G1 X124.478 Y105.522 E-.14464
G1 X124.478 Y104.682 E-.11638
M73 P71 R0
G1 X124.659 Y104.761 E-.02736
G1 X124.841 Y104.841 E-.02754
G1 X125.159 Y104.841 E-.04406
G1 X125.159 Y105.159 E-.04406
G1 X124.841 Y105.159 E-.04406
G1 X124.841 Y105.044 E-.01593
;WIPE_END
G1 E-.04669 F2100
G1 Z2.6 F720
;AFTER_LAYER_CHANGE
;2.6
M74 W0.027195

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
G1 X125.868 Y104.132 E.05876
M73 P72 R0
M73 Q72 S0
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
M73 P73 R0
M73 Q73 S0
G1 X126.275 Y103.725 E.08631
G1 X126.275 Y106.215 E.08428
M204 P2500
;WIPE_START
G1 F14400
M73 P74 R0
M73 Q74 S0
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z2.8 F720
G1 X125.044 Y105.159 F18000
G1 Z2.6 F720
G1 E.8 F2100
M204 P3000
;TYPE:Solid infill
;WIDTH:0.361285
G1 F900
G1 X125.159 Y105.159 E.00304
G1 X125.159 Y104.841 E.00842
G1 X124.841 Y104.841 E.00842
G1 X124.841 Y105.159 E.00842
M73 Q75 S0
;WIDTH:0.405642
G1 X124.761 Y105.341 E.006
;WIDTH:0.449999
G1 X124.682 Y105.522 E.00668
G1 X125.522 Y105.522 E.02843
G1 X125.522 Y104.478 E.03534
M73 P75 R0
G1 X124.478 Y104.478 E.03534
G1 X124.478 Y105.522 E.03534
M204 P2500
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.8
M201 X3999.97 Y3999.97

;WIPE_START
G1 F14400
G1 X124.478 Y104.478 E-.14464
G1 X125.522 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.14464
G1 X124.682 Y105.522 E-.11638
G1 X124.761 Y105.341 E-.02736
M73 Q76 S0
G1 X124.841 Y105.159 E-.02754
G1 X124.841 Y104.841 E-.04406
G1 X125.159 Y104.841 E-.04406
G1 X125.159 Y105.159 E-.04406
G1 X125.044 Y105.159 E-.01593
;WIPE_END
G1 E-.04669 F2100
G1 Z2.8 F720
M73 P76 R0
;AFTER_LAYER_CHANGE
;2.8
M74 W0.0294369

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M204 P3000
;TYPE:Perimeter
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
G1 X125.868 Y104.132 E.05876
G1 X125.868 Y105.808 E.05673
M73 Q77 S0
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 P77 R0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
G1 X126.275 Y103.725 E.08631
M73 P78 R0
M73 Q78 S0
G1 X126.275 Y106.215 E.08428
M204 P2500
;WIPE_START
G1 F14400
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
M73 Q79 S0
G1 X124.339 Y103.725 E-.08513
M73 P79 R0
;WIPE_END
G1 Z3 F720
G1 X124.841 Y105.044 F18000
G1 Z2.8 F720
G1 E.8 F2100
M204 P3000
;TYPE:Solid infill
;WIDTH:0.361285
G1 F900
G1 X124.841 Y105.159 E.00304
G1 X125.159 Y105.159 E.00842
G1 X125.159 Y104.841 E.00842
G1 X124.841 Y104.841 E.00842
;WIDTH:0.405642
G1 X124.659 Y104.761 E.006
;WIDTH:0.449999
G1 X124.478 Y104.682 E.00668
G1 X124.478 Y105.522 E.02843
G1 X125.522 Y105.522 E.03534
G1 X125.522 Y104.478 E.03534
M73 Q80 S0
G1 X124.478 Y104.478 E.03534
M73 P80 R0
M204 P2500
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;3
M201 X3999.97 Y3999.97

;WIPE_START
G1 F14400
G1 X125.522 Y104.478 E-.14464
G1 X125.522 Y105.522 E-.14464
G1 X124.478 Y105.522 E-.14464
G1 X124.478 Y104.682 E-.11638
G1 X124.659 Y104.761 E-.02736
G1 X124.841 Y104.841 E-.02754
G1 X125.159 Y104.841 E-.04406
G1 X125.159 Y105.159 E-.04406
G1 X124.841 Y105.159 E-.04406
G1 X124.841 Y105.044 E-.01593
;WIPE_END
G1 E-.04669 F2100
G1 Z3 F720
;AFTER_LAYER_CHANGE
;3
M74 W0.0316787

G1 X125.868 Y105.868 F18000
G1 E.8 F2100
M73 Q81 S0
M204 P3000
;TYPE:Perimeter
G1 F900
G1 X124.132 Y105.868 E.05876
G1 X124.132 Y104.132 E.05876
M73 P81 R0
G1 X125.868 Y104.132 E.05876
G1 X125.868 Y105.808 E.05673
M204 P2500
M204 T250
G1 X126.275 Y106.275 F18000
M73 Q82 S0
M204 T4000
M204 P3000
;TYPE:External perimeter
G1 F900
M73 P82 R0
G1 X123.725 Y106.275 E.08631
G1 X123.725 Y103.725 E.08631
G1 X126.275 Y103.725 E.08631
G1 X126.275 Y106.215 E.08428
M73 P83 R0
M73 Q83 S0
M204 P2500
;WIPE_START
G1 F14400
G1 X126.275 Y106.275 E-.00831
G1 X123.725 Y106.275 E-.35328
G1 X123.725 Y103.725 E-.35328
G1 X124.339 Y103.725 E-.08513
;WIPE_END
G1 Z3.2 F720
G1 X124.874 Y104.293 F18000
M73 Q84 S0
G1 Z3 F720
G1 E.8 F2100
M73 P84 R0
M204 P1500
;TYPE:Top solid infill
;WIDTH:0.453293
G1 F900
G1 X125.707 Y105.126 E.0402
M204 P2500
G1 X125.707 Y105.707 F18000
M204 P1500
G1 F900
G1 X124.293 Y104.293 E.06824
M204 P2500
G1 X124.293 Y104.874 F18000
M204 P1500
G1 F900
G1 X125.126 Y105.707 E.0402
M204 P2500
M486 S-1
;WIPE_START
G1 F14400;_WIPE
G1 X124.293 Y104.874 E-.16321
;WIPE_END
G1 E-.63679 F2100
M73 Q85 S0
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z4 F720 ; Move print head up
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 X241 Y201 F3600 ; park
M73 P85 R0
G1 Z26 F300 ; Move print head up
M73 P90 R0
M73 Q90 S0
G4 ; wait
M572 S0 ; reset PA
M593 X T2 F0 ; disable IS
M593 Y T2 F0 ; disable IS
M84 X Y E ; disable motors
; max_layer_z = 3
M73 P100 R0
M73 Q100 S0
; objects_info = {"objects":[{"name":"cube.stl","polygon":[[126.500,106.500],[123.500,106.500],[123.500,103.500],[126.500,103.500]]}]}
; filament used [mm] = 30.35
; filament used [cm3] = 0.07
; filament used [g] = 0.09
; filament cost = 0.00
; total filament used [g] = 0.09
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 47s
; estimated printing time (silent mode) = 48s
; estimated first layer printing time (normal mode) = 9s
; estimated first layer printing time (silent mode) = 9s

; prusaslicer_config = begin
; arc_fitting = emit_center
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; bed_temperature_extruder = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\nM201 X{interpolate_table(extruded_weight_total, (0,4000), (1400,2500), (20000,2500))} Y{interpolate_table(extruded_weight_total, (0,4000), (1400,2500), (20000,2500))}\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1500
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 50
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; colorprint_heights = 
; compatible_printers_condition_cummulative = "printer_notes=~/.*MK3.5.*/ and nozzle_diameter[0]==0.4 and ! single_extruder_multi_material";"nozzle_diameter[0]!=0.8 and printer_model==\"MK3.5\" and ! single_extruder_multi_material"
; complete_objects = 0
; cooling = 1
; cooling_perimeter_transition_distance = 0
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; custom_parameters_filament = ""
; custom_parameters_print = 
; custom_parameters_printer = 
; default_acceleration = 2500
; default_filament_profile = "Prusament PLA @MK3.5"
; default_print_profile = 0.20mm SPEED @MK3.5 0.4
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nG1 X241 Y201 F3600 ; park\n{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+23, max_print_height)} F300 ; Move print head up{endif}\nG4 ; wait\nM572 S0 ; reset PA\nM593 X T2 F0 ; disable IS\nM593 Y T2 F0 ; disable IS\nM84 X Y E ; disable motors\n; max_layer_z = [max_layer_z]
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 3000
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 150
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_abrasive = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 27.99
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_flush_speed = 0
; filament_flush_volume = 0
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = "Prusament PLA @MK3.5"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 278
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; filament_wipe = nil
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 500
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.5
; first_layer_height = 0.2
; first_layer_infill_speed = 100
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 230
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 120
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = firmware
; gcode_resolution = 0.008
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 4000
; infill_anchor = 2
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 15%
; infill_speed = 200
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\n{if ! spiral_vase}M74 W[extruded_weight_total]{endif}\n
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 2500,2500
; machine_max_acceleration_extruding = 4000,2500
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 4000,2500
; machine_max_acceleration_x = 4000,2500
; machine_max_acceleration_y = 4000,2500
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 300,160
; machine_max_feedrate_y = 300,160
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 5,5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 2,2
; machine_max_junction_deviation = 0,0
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 5
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_0.4n_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; over_bridge_speed = 50%
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 25
; overhang_speed_2 = 30
; overhang_speed_3 = 80%
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 3000
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 150
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = 0.20mm SPEED @MK3.5 0.4
; printer_model = MK3.5
; printer_notes = Don't remove the following keywords. \nPRINTER_MODEL_MK3.5\n
; printer_settings_id = Original Prusa MK3.5 & MK3.5S 0.4 nozzle
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.15
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 0
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 12
; small_perimeter_speed = 150
; solid_infill_acceleration = 3000
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 200
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "{if printer_notes!~/.*(MK3.5|MINIIS).*/}\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n{endif}\n\n{if printer_notes=~/.*MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.27{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}\n\n{if printer_notes=~/.*MK3.5.*/}\nM572 S{if nozzle_diameter[0]==0.4}0.035{elsif nozzle_diameter[0]==0.5}0.025{elsif nozzle_diameter[0]==0.6}0.02{elsif nozzle_diameter[0]==0.8}0.014{elsif nozzle_diameter[0]==0.25}0.12{elsif nozzle_diameter[0]==0.3}0.08{else}0{endif} ; Filament gcode\n{endif}"
; start_gcode = M17 ; enable steppers\nM862.1 P[nozzle_diameter] A{(filament_abrasive[0] ? 1 : 0)} F{(nozzle_high_flow[0] ? 1 : 0)} ; nozzle check\nM862.3 P "MK3.5" ; printer model check\nM862.5 P2 ; g-code level check\nM862.6 P"Input shaper" ; FW feature check\nM115 U6.5.7+12836\n\nM555 X{(min(print_bed_max[0], first_layer_print_min[0] + 32) - 32)} Y{(max(0, first_layer_print_min[1]) - 4)} W{((min(print_bed_max[0], max(first_layer_print_min[0] + 32, first_layer_print_max[0])))) - ((min(print_bed_max[0], first_layer_print_min[0] + 32) - 32))} H{((first_layer_print_max[1])) - ((max(0, first_layer_print_min[1]) - 4))}\n\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\n\nM140 S[first_layer_bed_temperature] ; set bed temp\nM104 T0 S170 ; set extruder temp for bed leveling\nM109 T0 R170 ; wait for temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\n\nG28 ; home all\n\nG29 P1 ; invalidate mbl & probe print area\nG29 P1 X23 Y5 W80 H20 C ; probe near purge place\nG29 P3.2 ; interpolate mbl probes\nG29 P3.13 ; extrapolate mbl outside probe area\nG29 A ; activate mbl\n\n; prepare for purge\nM104 S{first_layer_temperature[0]}\nG0 X0 Y-4 Z15 F4800 ; move away and ready for the purge\nM109 S{first_layer_temperature[0]}\n\n; Extrude purge line\n\nG92 E0 ; reset extruder position\nG0 E7 X15 Z0.2 F500 ; purge\nG0 X25 E4 F500 ; purge\nG0 X35 E4 F650 ; purge\nG0 X45 E4 F800 ; purge\nG0 X48 Z0.05 F8000 ; wipe, move close to the bed\nG0 X51 Z0.2 F8000 ; wipe, move quickly away from the bed\n\nG92 E0\nM221 S100 ; reset flow to 100%\n
; support_material = 1
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.4
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 3
; support_material_interface_pattern = auto
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 50%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 120
; support_material_style = snug
; support_material_synchronize_layers = 0
; support_material_threshold = 40
; support_material_with_sheath = 0
; support_material_xy_spacing = 80%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 8
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 30%
; temperature = 225
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 16x16/QOI, 313x173/QOI, 480x240/QOI, 380x285/PNG
; thumbnails_format = PNG
; toolchange_gcode = 
; toolchange_ordering = optimized
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.42
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 1500
; top_solid_infill_speed = 100
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 4000
; travel_lift_before_obstacle = 0
; travel_max_lift = 1.5
; travel_ramping_lift = 0
; travel_short_distance_acceleration = 250
; travel_slope = 1
; travel_speed = 300
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 25
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
