// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrinterService.Data;

#nullable disable

namespace PrinterService.Data.Migrations
{
    [DbContext(typeof(PSDbContext))]
    partial class PSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PrinterService.Model.Entities.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InvitedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HashedToken")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PSUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PrinterService.Model.Entities.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firmware")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadedMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrinterEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId", "JobId");

                    b.HasIndex("PrinterId", "Timestamp");

                    b.ToTable("PrinterEvents");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrinterLiveSlotState", b =>
                {
                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("HotendFanRpm")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<float?>("PrintFanRpm")
                        .HasColumnType("REAL");

                    b.Property<float?>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("PrinterId", "SlotNumber");

                    b.ToTable("PrinterLiveSlotStates");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrinterLiveState", b =>
                {
                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveSlot")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AmbientTemperature")
                        .HasColumnType("REAL");

                    b.Property<float?>("BedTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("ChamberFan1Rpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamberFan2Rpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamberFanPwmTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamberLedIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamberTargetTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ChamberTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("EnclosureFanRpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnclosureTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnclosureTimeInUse")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExtruderFan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtruderFilamentSensorStatus")
                        .HasColumnType("TEXT");

                    b.Property<float?>("FilamentUsed")
                        .HasColumnType("REAL");

                    b.Property<int?>("Flow")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("HeatbreakTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("MmuCommand")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MmuState")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("NozzleTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("PrintFan")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("PsuTemperature")
                        .HasColumnType("REAL");

                    b.Property<string>("RemoteFilamentSensorStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("TargetBedTemperature")
                        .HasColumnType("REAL");

                    b.Property<float?>("TargetNozzleTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("TimePrinting")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeToFilamentChange")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("XAxis")
                        .HasColumnType("REAL");

                    b.Property<float?>("YAxis")
                        .HasColumnType("REAL");

                    b.Property<float?>("ZAxis")
                        .HasColumnType("REAL");

                    b.HasKey("PrinterId");

                    b.ToTable("PrinterLiveStates");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrusaConnectAuthenticationData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FingerPrint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedToken")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporaryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TemporaryCodeExpiry")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TokenCreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FingerPrint")
                        .IsUnique();

                    b.HasIndex("PrinterId");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("TemporaryCode");

                    b.ToTable("PrusaConnectAuthentication");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.TeamMember", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanUse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"IsDefault\"");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.TelemetrySample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveSlot")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AmbientTemperature")
                        .HasColumnType("REAL");

                    b.Property<float?>("BedTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("ChamberFan1Rpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamberFan2Rpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamberFanPwmTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamberLedIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamberTargetTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ChamberTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("EnclosureFanRpm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnclosureTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnclosureTimeInUse")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExtruderFan")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("FilamentUsed")
                        .HasColumnType("REAL");

                    b.Property<int?>("Flow")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("HeatbreakTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("MmuCommand")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MmuState")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("NozzleTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("PrintFan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("PsuTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("TargetBedTemperature")
                        .HasColumnType("REAL");

                    b.Property<float?>("TargetNozzleTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("TimePrinting")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeToFilamentChange")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("XAxis")
                        .HasColumnType("REAL");

                    b.Property<float?>("YAxis")
                        .HasColumnType("REAL");

                    b.Property<float?>("ZAxis")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId", "Timestamp");

                    b.ToTable("TelemetrySamples");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.TelemetrySlotSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("HotendFanRpm")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<float?>("PrintFanRpm")
                        .HasColumnType("REAL");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelemetrySampleId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TelemetrySampleId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("TelemetrySlotSamples");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.PSUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.PSUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrinterService.Model.Entities.PSUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.PSUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrinterService.Model.Entities.Invitation", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.Printer", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrinterEvent", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrinterLiveSlotState", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.PrinterLiveState", "PrinterLiveState")
                        .WithMany("Slots")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrinterLiveState");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrinterLiveState", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.Printer", "Printer")
                        .WithOne()
                        .HasForeignKey("PrinterService.Model.Entities.PrinterLiveState", "PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrusaConnectAuthenticationData", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId");

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.TeamMember", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.TelemetrySample", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.TelemetrySlotSample", b =>
                {
                    b.HasOne("PrinterService.Model.Entities.TelemetrySample", "TelemetrySample")
                        .WithMany("Slots")
                        .HasForeignKey("TelemetrySampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelemetrySample");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.PrinterLiveState", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PrinterService.Model.Entities.TelemetrySample", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
