using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

using AwesomeAssertions;
using Homespool.Host.Services;
using Homespool.Model.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.DependencyInjection;
using OtpNet;

namespace Homespool.Host.E2ETest;

/// <summary>
/// Drives the real two-factor login flow over HTTP: <c>/Account/Login</c> redirecting a 2FA-enabled
/// account to <c>/Account/LoginWith2fa</c> instead of signing it in directly, then that page's own
/// accept/reject/lockout behaviour. Closes the gap raised alongside <see cref="LoginFlowTests"/>:
/// <c>LoginWith2faModel</c> had no test of any kind, and unlike external login (no OAuth/OIDC scheme
/// is registered anywhere in <c>Program.cs</c>), 2FA is genuinely reachable - a signed-in user can
/// turn it on via <c>Manage/EnableAuthenticator</c>.
/// </summary>
/// <remarks>
/// The TOTP algorithm itself (RFC 6238) is entirely ASP.NET Core Identity's - this project supplies
/// no cryptography of its own, only the Razor Pages wiring around
/// <see cref="UserManager{TUser}.VerifyTwoFactorTokenAsync"/> and friends (see
/// <c>EnableAuthenticatorModel</c>). A valid test code is computed the same way a real authenticator
/// app would - via <c>Otp.NET</c>, a standard RFC 6238 library, against the seeded user's shared
/// secret - trusting the standard implementation exactly as <c>SmtpEmailSenderTests</c> trusts
/// MailKit's wire protocol, rather than reimplementing RFC 6238 in the test.
/// <see cref="UserManager{TUser}.GenerateTwoFactorTokenAsync"/> was tried first and doesn't work here:
/// <c>AuthenticatorTokenProvider</c> only implements <em>validation</em>, since in production the code
/// is generated by the user's own app, never by this server.
/// </remarks>
[Collection("WebApplicationFactory")]
public sealed class LoginWith2faTests : IAsyncLifetime, IDisposable
{
    private const string Password = "Correct-Horse-Battery-Staple-1!";
    private const string Email = "twofactor@example.com";

    private readonly string _databasePath = Path.Combine(Path.GetTempPath(), $"ps-2fa-{Guid.NewGuid():N}.db");
    private HomespoolFactory _factory = null!;

    private static FormUrlEncodedContent TwoFactorBody(string antiforgeryToken, string code) => new(new Dictionary<string, string>
    {
        ["__RequestVerificationToken"] = antiforgeryToken,
        ["RememberMe"] = "false",
        ["Input.TwoFactorCode"] = code,
    });

    public Task InitializeAsync()
    {
        _factory = new HomespoolFactory($"Data Source={_databasePath}");
        _ = _factory.Server;

        using IServiceScope scope = _factory.Services.CreateScope();
        scope.ServiceProvider.GetRequiredService<SetupState>().MarkComplete();

        return Task.CompletedTask;
    }

    public Task DisposeAsync()
    {
        Dispose();

        return Task.CompletedTask;
    }

    // CA1001 wants IDisposable on a type owning a disposable field even though xUnit's IAsyncLifetime
    // already drives cleanup via DisposeAsync above; WebApplicationFactory.Dispose is idempotent, so
    // this is a safe, redundant satisfier rather than a second real teardown path.
    public void Dispose()
    {
        _factory.Dispose();

        foreach (string path in new[] { _databasePath, _databasePath + "-wal", _databasePath + "-shm" })
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
    }

    /// <summary>
    /// Seeds a confirmed account and enables 2FA on it directly via <see cref="UserManager{TUser}"/> -
    /// the same shortcut past <c>Manage/EnableAuthenticator</c>'s own form <see cref="LoginFlowTests"/>
    /// takes past <c>Register</c>'s: this suite verifies login, not enrolment.
    /// </summary>
    private async Task CreateTwoFactorEnabledUserAsync()
    {
        using IServiceScope scope = _factory.Services.CreateScope();

        IUserStore<HSUser> userStore = scope.ServiceProvider.GetRequiredService<IUserStore<HSUser>>();
        IUserEmailStore<HSUser> emailStore = (IUserEmailStore<HSUser>)userStore;
        UserManager<HSUser> userManager = scope.ServiceProvider.GetRequiredService<UserManager<HSUser>>();

        HSUser user = new();
        await userStore.SetUserNameAsync(user, Email, CancellationToken.None);
        await emailStore.SetEmailAsync(user, Email, CancellationToken.None);
        user.EmailConfirmed = true;

        IdentityResult createResult = await userManager.CreateAsync(user, Password);
        createResult.Succeeded.Should().BeTrue("account creation is setup for this test, not what it verifies");

        IdentityResult keyResult = await userManager.ResetAuthenticatorKeyAsync(user);
        keyResult.Succeeded.Should().BeTrue();

        IdentityResult enableResult = await userManager.SetTwoFactorEnabledAsync(user, true);
        enableResult.Succeeded.Should().BeTrue();
    }

    /// <summary>
    /// A currently-valid TOTP code for the seeded user's authenticator secret, computed with
    /// <c>Otp.NET</c> - a standard RFC 6238 implementation - against the same base32 secret
    /// <c>EnableAuthenticatorModel</c> hands out via <see cref="UserManager{TUser}.GetAuthenticatorKeyAsync"/>.
    /// </summary>
    /// <remarks>
    /// <b>Not <see cref="UserManager{TUser}.GenerateTwoFactorTokenAsync"/></b> - that doesn't work for
    /// <c>AuthenticatorTokenProvider</c>, which only implements <em>validation</em>: in production the
    /// code is generated by the user's own authenticator app, never by this server, so there was
    /// nothing to test against until this returned <c>null</c> for the very first version of this
    /// test. A real TOTP library is used deliberately rather than hand-rolling RFC 6238 to work around
    /// that, for the same "trust the standard implementation" reasoning as the SMTP tests trusting
    /// MailKit's wire protocol.
    /// </remarks>
    private async Task<string> GenerateValidAuthenticatorCodeAsync()
    {
        using IServiceScope scope = _factory.Services.CreateScope();

        UserManager<HSUser> userManager = scope.ServiceProvider.GetRequiredService<UserManager<HSUser>>();
        HSUser user = await userManager.FindByEmailAsync(Email)
                      ?? throw new InvalidOperationException($"No user seeded for {Email}.");

        string base32Key = await userManager.GetAuthenticatorKeyAsync(user)
                            ?? throw new InvalidOperationException("No authenticator key set for the seeded user.");

        byte[] secretBytes = Base32Encoding.ToBytes(base32Key);

        return new Totp(secretBytes).ComputeTotp();
    }

    /// <summary>
    /// Signs in with the seeded user's password and follows the redirect to
    /// <c>/Account/LoginWith2fa</c>, returning the client (cookies intact - the pending-2FA identity
    /// is carried by a cookie, not anything in the URL) and the antiforgery token off that page.
    /// </summary>
    private async Task<(HttpClient client, string antiforgeryToken)> SignInWithPasswordAsync()
    {
        HttpClient client = _factory.CreateClient(new WebApplicationFactoryClientOptions { AllowAutoRedirect = false });

        HttpResponseMessage loginGet = await client.GetAsync("/Account/Login");
        string loginAntiforgeryToken = AntiforgeryTestHelper.ExtractToken(await loginGet.Content.ReadAsStringAsync());

        using FormUrlEncodedContent loginBody = new(new Dictionary<string, string>
        {
            ["__RequestVerificationToken"] = loginAntiforgeryToken,
            ["Input.Email"] = Email,
            ["Input.Password"] = Password,
        });

        HttpResponseMessage loginPostResponse = await client.PostAsync("/Account/Login", loginBody);

        loginPostResponse.StatusCode.Should().Be(HttpStatusCode.Redirect, "a 2FA-enabled account still redirects, just not to the app root");
        loginPostResponse.Headers.Location!.OriginalString.Should().StartWith("/Account/LoginWith2fa");
        IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, loginPostResponse).Should()
            .BeFalse("the password alone must not complete sign-in for a 2FA-enabled account");

        HttpResponseMessage twoFactorGet = await client.GetAsync(loginPostResponse.Headers.Location);
        twoFactorGet.StatusCode.Should().Be(HttpStatusCode.OK);
        string twoFactorAntiforgeryToken = AntiforgeryTestHelper.ExtractToken(await twoFactorGet.Content.ReadAsStringAsync());

        return (client, twoFactorAntiforgeryToken);
    }

    /// <summary>
    /// The full happy path: correct password redirects to the 2FA page rather than signing in, and a
    /// valid authenticator code completes sign-in from there.
    /// </summary>
    [Fact]
    public async Task EnteringAValidAuthenticatorCodeCompletesSignIn()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        (HttpClient client, string antiforgeryToken) = await SignInWithPasswordAsync();
        using (client)
        {
            string code = await GenerateValidAuthenticatorCodeAsync();
            using FormUrlEncodedContent body = TwoFactorBody(antiforgeryToken, code);

            // Act
            HttpResponseMessage postResponse = await client.PostAsync("/Account/LoginWith2fa", body);

            // Assert
            postResponse.StatusCode.Should().Be(HttpStatusCode.Redirect, "a valid code completes sign-in and redirects to the return URL");
            postResponse.Headers.Location!.OriginalString.Should().Be("/");
            IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, postResponse).Should()
                .BeTrue("a valid authenticator code must issue the Identity application cookie");
        }
    }

    /// <summary>An invalid code is rejected without signing in - well below the lockout threshold.</summary>
    [Fact]
    public async Task EnteringAnInvalidAuthenticatorCodeIsRejectedWithoutSigningIn()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        (HttpClient client, string antiforgeryToken) = await SignInWithPasswordAsync();
        using (client)
        {
            using FormUrlEncodedContent body = TwoFactorBody(antiforgeryToken, "000000");

            // Act
            HttpResponseMessage postResponse = await client.PostAsync("/Account/LoginWith2fa", body);

            // Assert
            postResponse.StatusCode.Should().Be(HttpStatusCode.OK, "a rejected code re-renders the page rather than redirecting");
            IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, postResponse).Should().BeFalse();

            string html = await postResponse.Content.ReadAsStringAsync();
            html.Should().Contain("Invalid authenticator code");
        }
    }

    /// <summary>
    /// Unlike a wrong password on <c>Login</c> (<c>lockoutOnFailure: false</c>, deliberately), a wrong
    /// 2FA code counts toward Identity's default lockout threshold -
    /// <c>TwoFactorAuthenticatorSignInAsync</c> takes no such override. Enough wrong codes locks the
    /// account out and redirects to <c>/Account/Lockout</c>.
    /// </summary>
    [Fact]
    public async Task RepeatedInvalidCodesEventuallyLockTheAccountOut()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        (HttpClient client, string antiforgeryToken) = await SignInWithPasswordAsync();
        using (client)
        {
            HttpResponseMessage? lastResponse = null;

            // Act - Identity's default MaxFailedAccessAttempts is 5; loop with headroom rather than
            // hardcoding that exact number, so this doesn't silently stop testing anything if it's
            // ever tuned differently.
            for (int attempt = 0; attempt < 10; attempt++)
            {
                using FormUrlEncodedContent body = TwoFactorBody(antiforgeryToken, "000000");
                lastResponse = await client.PostAsync("/Account/LoginWith2fa", body);

                if (lastResponse.StatusCode == HttpStatusCode.Redirect)
                {
                    break;
                }
            }

            // Assert
            lastResponse.Should().NotBeNull();
            lastResponse!.StatusCode.Should().Be(HttpStatusCode.Redirect, "enough failed codes must eventually lock the account out");
            lastResponse.Headers.Location!.OriginalString.Should().Be("/Account/Lockout");
        }
    }
}
