using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading;
using System.Threading.Tasks;

using AwesomeAssertions;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;

using OtpNet;

using Homespool.Host.Accounts;
using Homespool.Host.Localisation;
using Homespool.Model.Entities;

namespace Homespool.Host.E2ETest;

/// <summary>
/// Drives the real two-factor login flow over HTTP: <c>/Account/Login</c> redirecting a 2FA-enabled
/// account to <c>/Account/LoginWith2fa</c> instead of signing it in directly, then that page's own
/// accept/reject/lockout behaviour. Closes the gap raised alongside <see cref="LoginFlowTests"/>:
/// <c>LoginWith2faModel</c> had no test of any kind, and unlike external login (no OAuth/OIDC scheme
/// is registered anywhere in <c>Program.cs</c>), 2FA is genuinely reachable - a signed-in user can
/// turn it on via <c>Manage/EnableAuthenticator</c>.
/// </summary>
/// <remarks>
/// The TOTP algorithm itself (RFC 6238) is entirely ASP.NET Core Identity's - this project supplies
/// no cryptography of its own, only the Razor Pages wiring around
/// <see cref="UserManager{TUser}.VerifyTwoFactorTokenAsync"/> and friends (see
/// <c>EnableAuthenticatorModel</c>). A valid test code is computed the same way a real authenticator
/// app would - via <c>Otp.NET</c>, a standard RFC 6238 library, against the seeded user's shared
/// secret - trusting the standard implementation exactly as <c>SmtpEmailSenderTests</c> trusts
/// MailKit's wire protocol, rather than reimplementing RFC 6238 in the test.
/// <see cref="UserManager{TUser}.GenerateTwoFactorTokenAsync"/> was tried first and doesn't work here:
/// <c>AuthenticatorTokenProvider</c> only implements <em>validation</em>, since in production the code
/// is generated by the user's own app, never by this server.
/// </remarks>
public sealed class LoginWith2faTests : IAsyncLifetime
{
    private const string Password = "Correct-Horse-Battery-Staple-1!";
    private const string Email = "twofactor@example.com";

    private readonly ScratchDirectory _scratch = ScratchDirectory.Create("2fa");
    private HomespoolFactory _factory = null!;

    private static FormUrlEncodedContent TwoFactorBody(string antiforgeryToken, string code)
    {
        return new(new Dictionary<string, string>
        {
            ["__RequestVerificationToken"] = antiforgeryToken,
            ["RememberMe"] = "false",
            ["Input.TwoFactorCode"] = code,
        });
    }

    public ValueTask InitializeAsync()
    {
        _factory = new HomespoolFactory(_scratch);
        _ = _factory.Server;

        using IServiceScope scope = _factory.Services.CreateScope();
        scope.ServiceProvider.GetRequiredService<SetupState>().MarkComplete();

        return ValueTask.CompletedTask;
    }

    public async ValueTask DisposeAsync()
    {
        await _factory.DisposeAsync();

        _scratch.Dispose();
    }

    // CA1001 wants IDisposable on a type owning a disposable field even though xUnit's IAsyncLifetime
    // already drives cleanup via DisposeAsync above; WebApplicationFactory.Dispose is idempotent, so
    // this is a safe, redundant satisfier rather than a second real teardown path.

    /// <summary>
    /// Seeds a confirmed account and enables 2FA on it directly via <see cref="UserManager{TUser}"/> -
    /// the same shortcut past <c>Manage/EnableAuthenticator</c>'s own form <see cref="LoginFlowTests"/>
    /// takes past <c>Register</c>'s: this suite verifies login, not enrolment.
    /// </summary>
    private async Task CreateTwoFactorEnabledUserAsync()
    {
        using IServiceScope scope = _factory.Services.CreateScope();

        IUserStore<HSUser> userStore = scope.ServiceProvider.GetRequiredService<IUserStore<HSUser>>();
        IUserEmailStore<HSUser> emailStore = (IUserEmailStore<HSUser>)userStore;
        UserManager<HSUser> userManager = scope.ServiceProvider.GetRequiredService<UserManager<HSUser>>();

        HSUser user = new();
        await userStore.SetUserNameAsync(user, EnrolmentFlowHelper.UsernameFor(Email), CancellationToken.None);
        await emailStore.SetEmailAsync(user, Email, CancellationToken.None);
        user.EmailConfirmed = true;

        IdentityResult createResult = await userManager.CreateAsync(user, Password);
        createResult.Succeeded.Should().BeTrue("account creation is setup for this test, not what it verifies");

        IdentityResult keyResult = await userManager.ResetAuthenticatorKeyAsync(user);
        keyResult.Succeeded.Should().BeTrue();

        IdentityResult enableResult = await userManager.SetTwoFactorEnabledAsync(user, true);
        enableResult.Succeeded.Should().BeTrue();
    }

    /// <summary>
    /// A currently-valid TOTP code for the seeded user's authenticator secret, computed with
    /// <c>Otp.NET</c> - a standard RFC 6238 implementation - against the same base32 secret
    /// <c>EnableAuthenticatorModel</c> hands out via <see cref="UserManager{TUser}.GetAuthenticatorKeyAsync"/>.
    /// </summary>
    /// <remarks>
    /// <b>Not <see cref="UserManager{TUser}.GenerateTwoFactorTokenAsync"/></b> - that doesn't work for
    /// <c>AuthenticatorTokenProvider</c>, which only implements <em>validation</em>: in production the
    /// code is generated by the user's own authenticator app, never by this server, so there was
    /// nothing to test against until this returned <c>null</c> for the very first version of this
    /// test. A real TOTP library is used deliberately rather than hand-rolling RFC 6238 to work around
    /// that, for the same "trust the standard implementation" reasoning as the SMTP tests trusting
    /// MailKit's wire protocol.
    /// </remarks>
    private async Task<string> GenerateValidAuthenticatorCodeAsync()
    {
        using IServiceScope scope = _factory.Services.CreateScope();

        UserManager<HSUser> userManager = scope.ServiceProvider.GetRequiredService<UserManager<HSUser>>();
        HSUser user = await userManager.FindByEmailAsync(Email) ??
                      throw new InvalidOperationException($"No user seeded for {Email}.");

        string base32Key = await userManager.GetAuthenticatorKeyAsync(user) ??
                           throw new InvalidOperationException("No authenticator key set for the seeded user.");

        byte[] secretBytes = Base32Encoding.ToBytes(base32Key);

        return new Totp(secretBytes).ComputeTotp();
    }

    /// <summary>
    /// Signs in with the seeded user's password and follows the redirect to
    /// <c>/Account/LoginWith2fa</c>, returning the client (cookies intact - the pending-2FA identity
    /// is carried by a cookie, not anything in the URL) and the antiforgery token off that page.
    /// </summary>
    private async Task<(HttpClient client, string antiforgeryToken)> SignInWithPasswordAsync()
    {
        HttpClient client = _factory.CreateClient(new WebApplicationFactoryClientOptions { AllowAutoRedirect = false });

        HttpResponseMessage loginGet = await client.GetAsync("/Account/Login");
        string loginAntiforgeryToken =
            AntiforgeryTestHelper.ExtractToken(await loginGet.Content.ReadAsStringAsync(TestContext.Current.CancellationToken));

        using FormUrlEncodedContent loginBody = new(new Dictionary<string, string>
        {
            ["__RequestVerificationToken"] = loginAntiforgeryToken,
            ["Input.Login"] = Email,
            ["Input.Password"] = Password,
        });

        HttpResponseMessage loginPostResponse = await client.PostAsync("/Account/Login", loginBody);

        loginPostResponse.StatusCode.Should()
                         .Be(HttpStatusCode.Redirect, "a 2FA-enabled account still redirects, just not to the app root");
        loginPostResponse.Headers.Location!.OriginalString.Should().StartWith("/Account/LoginWith2fa");
        IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, loginPostResponse).Should()
                                .BeFalse("the password alone must not complete sign-in for a 2FA-enabled account");

        HttpResponseMessage twoFactorGet = await client.GetAsync(loginPostResponse.Headers.Location);
        twoFactorGet.StatusCode.Should().Be(HttpStatusCode.OK);
        string twoFactorAntiforgeryToken =
            AntiforgeryTestHelper.ExtractToken(await twoFactorGet.Content.ReadAsStringAsync(TestContext.Current.CancellationToken));

        return (client, twoFactorAntiforgeryToken);
    }

    /// <summary>
    /// The full happy path: correct password redirects to the 2FA page rather than signing in, and a
    /// valid authenticator code completes sign-in from there.
    /// </summary>
    [Fact]
    public async Task EnteringAValidAuthenticatorCodeCompletesSignIn()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        (HttpClient client, string antiforgeryToken) = await SignInWithPasswordAsync();
        using (client)
        {
            string code = await GenerateValidAuthenticatorCodeAsync();
            using FormUrlEncodedContent body = TwoFactorBody(antiforgeryToken, code);

            // Act
            HttpResponseMessage postResponse =
                await client.PostAsync("/Account/LoginWith2fa", body, TestContext.Current.CancellationToken);

            // Assert
            postResponse.StatusCode.Should()
                        .Be(HttpStatusCode.Redirect, "a valid code completes sign-in and redirects to the return URL");
            postResponse.Headers.Location!.OriginalString.Should().Be("/");
            IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, postResponse).Should()
                                    .BeTrue("a valid authenticator code must issue the Identity application cookie");
        }
    }

    /// <summary>An invalid code is rejected without signing in - well below the lockout threshold.</summary>
    [Fact]
    public async Task EnteringAnInvalidAuthenticatorCodeIsRejectedWithoutSigningIn()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        (HttpClient client, string antiforgeryToken) = await SignInWithPasswordAsync();
        using (client)
        {
            using FormUrlEncodedContent body = TwoFactorBody(antiforgeryToken, "000000");

            // Act
            HttpResponseMessage postResponse =
                await client.PostAsync("/Account/LoginWith2fa", body, TestContext.Current.CancellationToken);

            // Assert
            postResponse.StatusCode.Should().Be(HttpStatusCode.OK, "a rejected code re-renders the page rather than redirecting");
            IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, postResponse).Should().BeFalse();

            string html = await postResponse.Content.ReadAsStringAsync(TestContext.Current.CancellationToken);
            html.Should().Contain("Invalid authenticator code");
        }
    }

    /// <summary>
    /// A wrong code counts toward Identity's default lockout threshold, as a wrong password does.
    /// Enough wrong codes locks the account out and redirects to <c>/Account/Lockout</c>.
    /// </summary>
    [Fact]
    public async Task RepeatedInvalidCodesEventuallyLockTheAccountOut()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        (HttpClient client, string antiforgeryToken) = await SignInWithPasswordAsync();
        using (client)
        {
            HttpResponseMessage? lastResponse = null;

            // Act - Identity's default MaxFailedAccessAttempts is 5; loop with headroom rather than
            // hardcoding that exact number, so this doesn't silently stop testing anything if it's
            // ever tuned differently.
            for (int attempt = 0; attempt < 10; attempt++)
            {
                using FormUrlEncodedContent body = TwoFactorBody(antiforgeryToken, "000000");
                lastResponse = await client.PostAsync("/Account/LoginWith2fa", body, TestContext.Current.CancellationToken);

                if (lastResponse.StatusCode == HttpStatusCode.Redirect)
                {
                    break;
                }
            }

            // Assert
            lastResponse.Should().NotBeNull();
            lastResponse!.StatusCode.Should()
                         .Be(HttpStatusCode.Redirect, "enough failed codes must eventually lock the account out");
            lastResponse.Headers.Location!.OriginalString.Should().Be("/Account/Lockout");
        }
    }

    /// <summary>
    /// "Remember this machine" is a cookie for the browser, not the session: the next password sign-in
    /// on the same browser completes without asking for a code.
    /// </summary>
    [Fact]
    public async Task ARememberedBrowserIsNotAskedForACodeNextTime()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        (HttpClient client, string antiforgeryToken) = await SignInWithPasswordAsync();
        using (client)
        {
            using FormUrlEncodedContent remembered = new(new Dictionary<string, string>
            {
                ["__RequestVerificationToken"] = antiforgeryToken,
                ["RememberMe"] = "false",
                ["Input.TwoFactorCode"] = await GenerateValidAuthenticatorCodeAsync(),
                ["Input.RememberMachine"] = "true",
            });
            HttpResponseMessage completed = await client.PostAsync("/Account/LoginWith2fa", remembered, TestContext.Current.CancellationToken);
            completed.StatusCode.Should().Be(HttpStatusCode.Redirect, "the code was right, so this is setup rather than what the test verifies");

            HttpResponseMessage loginGet = await client.GetAsync("/Account/Login", TestContext.Current.CancellationToken);
            string loginToken = AntiforgeryTestHelper.ExtractToken(await loginGet.Content.ReadAsStringAsync(TestContext.Current.CancellationToken));
            using FormUrlEncodedContent loginBody = new(new Dictionary<string, string>
            {
                ["__RequestVerificationToken"] = loginToken,
                ["Input.Login"] = Email,
                ["Input.Password"] = Password,
            });

            // Act
            HttpResponseMessage again = await client.PostAsync("/Account/Login", loginBody, TestContext.Current.CancellationToken);

            // Assert
            again.StatusCode.Should().Be(HttpStatusCode.Redirect);
            again.Headers.Location!.OriginalString.Should().Be("/", "a remembered browser owes no code, so the password alone completes the sign-in");
            IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, again).Should().BeTrue();
        }
    }

    /// <summary>
    /// The way back in without the authenticator: a recovery code completes the sign-in from the
    /// pending step, and is spent by it - the same code is refused the second time.
    /// </summary>
    [Fact]
    public async Task ARecoveryCodeCompletesSignInOnceAndIsThenSpent()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        string recoveryCode;

        using (IServiceScope scope = _factory.Services.CreateScope())
        {
            UserManager<HSUser> userManager = scope.ServiceProvider.GetRequiredService<UserManager<HSUser>>();
            HSUser user = (await userManager.FindByEmailAsync(Email))!;
            recoveryCode = (await userManager.GenerateNewTwoFactorRecoveryCodesAsync(user, 2))!.First();
        }

        // Act
        HttpResponseMessage first = await RedeemAsync(recoveryCode);
        HttpResponseMessage second = await RedeemAsync(recoveryCode);

        // Assert
        first.StatusCode.Should().Be(HttpStatusCode.Redirect, "a valid recovery code completes the sign-in");
        first.Headers.Location!.OriginalString.Should().Be("/");
        IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, first).Should().BeTrue();

        second.StatusCode.Should().Be(HttpStatusCode.OK, "a spent code re-renders the page rather than redirecting");
        IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, second).Should().BeFalse();
        (await second.Content.ReadAsStringAsync(TestContext.Current.CancellationToken)).Should().Contain("Invalid recovery code");
    }

    /// <summary>
    /// A <c>returnUrl</c> off this site does not stop a valid recovery code from signing in: the code
    /// is spent by the sign-in, so an error page here would cost the person a code for nothing.
    /// </summary>
    [Fact]
    public async Task ARecoveryCodeWithANonLocalReturnUrlSignsInAndGoesHome()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        string recoveryCode;

        using (IServiceScope scope = _factory.Services.CreateScope())
        {
            UserManager<HSUser> userManager = scope.ServiceProvider.GetRequiredService<UserManager<HSUser>>();
            HSUser user = (await userManager.FindByEmailAsync(Email))!;
            recoveryCode = (await userManager.GenerateNewTwoFactorRecoveryCodesAsync(user, 2))!.First();
        }

        // Act
        HttpResponseMessage response = await RedeemAsync(recoveryCode, "https://evil.example/");

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.Redirect);
        response.Headers.Location!.OriginalString.Should().Be("/");
        IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, response).Should().BeTrue();
    }

    /// <summary>Passes the password step on a fresh browser, then posts <paramref name="recoveryCode"/> to the recovery page.</summary>
    private async Task<HttpResponseMessage> RedeemAsync(string recoveryCode, string? returnUrl = null)
    {
        (HttpClient client, _) = await SignInWithPasswordAsync();
        using (client)
        {
            HttpResponseMessage recoveryGet = await client.GetAsync("/Account/LoginWithRecoveryCode", TestContext.Current.CancellationToken);
            recoveryGet.StatusCode.Should().Be(HttpStatusCode.OK, "the pending account may choose the recovery page instead of the code page");
            string token = AntiforgeryTestHelper.ExtractToken(await recoveryGet.Content.ReadAsStringAsync(TestContext.Current.CancellationToken));

            using FormUrlEncodedContent body = new(new Dictionary<string, string>
            {
                ["__RequestVerificationToken"] = token,
                ["Input.RecoveryCode"] = recoveryCode,
            });

            string target = returnUrl is null ? "/Account/LoginWithRecoveryCode" : $"/Account/LoginWithRecoveryCode?returnUrl={Uri.EscapeDataString(returnUrl)}";

            return await client.PostAsync(target, body, TestContext.Current.CancellationToken);
        }
    }

    /// <summary>
    /// A browser with nothing pending - the password step's cookie ran out, or was never written - is
    /// sent back to the login page with the return address it came with, and the login page says why.
    /// </summary>
    [Theory]
    [InlineData("/Account/LoginWith2fa")]
    [InlineData("/Account/LoginWithRecoveryCode")]
    public async Task OpeningACodePageWithNothingPendingGoesBackToTheLoginPage(string page)
    {
        // Arrange
        using HttpClient client = _factory.CreateClient(new WebApplicationFactoryClientOptions { AllowAutoRedirect = false });

        // Act
        HttpResponseMessage response = await client.GetAsync($"{page}?returnUrl=%2FPrinters", TestContext.Current.CancellationToken);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.Redirect, "nothing is pending, so there is no code to ask for");
        response.Headers.Location!.OriginalString.Should().Be("/Account/Login?ReturnUrl=%2FPrinters");

        HttpResponseMessage login = await client.GetAsync(response.Headers.Location, TestContext.Current.CancellationToken);
        (await login.Content.ReadAsStringAsync(TestContext.Current.CancellationToken)).Should()
            .Contain("The sign-in timed out before the code was entered.");
    }

    /// <summary>
    /// A code posted with nothing pending goes back to the login page too - including an empty one,
    /// which would otherwise be answered with a validation message on a page that cannot be finished.
    /// </summary>
    [Theory]
    [InlineData("/Account/LoginWith2fa", "Input.TwoFactorCode", "000000")]
    [InlineData("/Account/LoginWith2fa", "Input.TwoFactorCode", "")]
    [InlineData("/Account/LoginWithRecoveryCode", "Input.RecoveryCode", "AAAAA-BBBBB")]
    [InlineData("/Account/LoginWithRecoveryCode", "Input.RecoveryCode", "")]
    public async Task PostingACodeWithNothingPendingGoesBackToTheLoginPage(string page, string field, string code)
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        using HttpClient client = _factory.CreateClient(new WebApplicationFactoryClientOptions { AllowAutoRedirect = false });

        HttpResponseMessage loginGet = await client.GetAsync("/Account/Login", TestContext.Current.CancellationToken);
        string token = AntiforgeryTestHelper.ExtractToken(await loginGet.Content.ReadAsStringAsync(TestContext.Current.CancellationToken));

        using FormUrlEncodedContent body = new(new Dictionary<string, string>
        {
            ["__RequestVerificationToken"] = token,
            [field] = code,
        });

        // Act
        HttpResponseMessage response = await client.PostAsync(page, body, TestContext.Current.CancellationToken);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.Redirect, "nothing is pending, so there is no account to present the code for");
        response.Headers.Location!.OriginalString.Should().Be("/Account/Login");
        IdentityCookieTestHelper.SetTheApplicationCookie(_factory.Services, response).Should().BeFalse();
    }

    /// <summary>
    /// A password changed from a remembered browser keeps that browser signed in. The change moves the
    /// stamp, so the browser is no longer remembered - but finding that out, which the two-factor page
    /// does, must not end the session the change just refreshed.
    /// </summary>
    [Fact]
    public async Task AChangedPasswordForgetsTheRememberedBrowserAndKeepsTheSession()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        using HttpClient client = await SignInRememberedAsync();

        string form = await client.GetStringAsync("/Account/Manage/ChangePassword", TestContext.Current.CancellationToken);
        using FormUrlEncodedContent body = new(new Dictionary<string, string>
        {
            ["__RequestVerificationToken"] = AntiforgeryTestHelper.ExtractToken(form),
            ["Input.OldPassword"] = Password,
            ["Input.NewPassword"] = Password + "-changed",
            ["Input.ConfirmPassword"] = Password + "-changed",
        });
        HttpResponseMessage changed = await client.PostAsync("/Account/Manage/ChangePassword", body, TestContext.Current.CancellationToken);
        changed.StatusCode.Should().Be(HttpStatusCode.Redirect, "the change itself is setup");

        // Act
        bool remembered = await IsRememberedAsync(client);

        // Assert
        remembered.Should().BeFalse("a password change moves the stamp the remembered cookie was written under");
        (await client.GetAsync("/Account/Manage", TestContext.Current.CancellationToken)).StatusCode
            .Should().Be(HttpStatusCode.OK, "forgetting the browser is not signing it out");
    }

    /// <summary>
    /// A rename moves the stamp but leaves the second factor where it was, so the browser that made it
    /// stays remembered, and stays signed in.
    /// </summary>
    [Fact]
    public async Task ARenameKeepsTheBrowserRemembered()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        using HttpClient client = await SignInRememberedAsync();

        string form = await client.GetStringAsync("/Account/Manage", TestContext.Current.CancellationToken);
        using FormUrlEncodedContent body = new(new Dictionary<string, string>
        {
            ["__RequestVerificationToken"] = AntiforgeryTestHelper.ExtractToken(form),
            ["Input.Username"] = "renamed",
        });
        HttpResponseMessage renamed = await client.PostAsync("/Account/Manage", body, TestContext.Current.CancellationToken);
        renamed.StatusCode.Should().Be(HttpStatusCode.Redirect, "the rename itself is setup");

        // Act
        bool remembered = await IsRememberedAsync(client);

        // Assert
        remembered.Should().BeTrue("the remembered cookie was re-issued on the new stamp");
        (await client.GetAsync("/Account/Manage", TestContext.Current.CancellationToken)).StatusCode.Should().Be(HttpStatusCode.OK);
    }

    /// <summary>
    /// An address change confirmed in the remembered browser moves the stamp but leaves the second factor
    /// where it was, so that browser stays remembered, and stays signed in.
    /// </summary>
    [Fact]
    public async Task AConfirmedEmailChangeKeepsTheBrowserRemembered()
    {
        // Arrange
        await CreateTwoFactorEnabledUserAsync();
        using HttpClient client = await SignInRememberedAsync();

        HttpResponseMessage confirmed = await client.GetAsync(await ConfirmEmailChangeUrlAsync("moved@example.com"), TestContext.Current.CancellationToken);
        confirmed.StatusCode.Should().Be(HttpStatusCode.OK, "the confirmation itself is setup");

        using (IServiceScope scope = _factory.Services.CreateScope())
        {
            (await scope.ServiceProvider.GetRequiredService<UserManager<HSUser>>().FindByEmailAsync("moved@example.com"))
                .Should().NotBeNull("a refused change renders the same page, so the address is checked");
        }

        // Act
        bool remembered = await IsRememberedAsync(client);

        // Assert
        remembered.Should().BeTrue("the remembered cookie was re-issued on the new stamp");
        (await client.GetAsync("/Account/Manage", TestContext.Current.CancellationToken)).StatusCode.Should().Be(HttpStatusCode.OK);
    }

    /// <summary>
    /// Signs the seeded user in with the password and a code, asking for the browser to be remembered,
    /// and returns the signed-in client.
    /// </summary>
    private async Task<HttpClient> SignInRememberedAsync()
    {
        (HttpClient client, string antiforgeryToken) = await SignInWithPasswordAsync();

        using FormUrlEncodedContent remembered = new(new Dictionary<string, string>
        {
            ["__RequestVerificationToken"] = antiforgeryToken,
            ["RememberMe"] = "false",
            ["Input.TwoFactorCode"] = await GenerateValidAuthenticatorCodeAsync(),
            ["Input.RememberMachine"] = "true",
        });
        HttpResponseMessage completed = await client.PostAsync("/Account/LoginWith2fa", remembered, TestContext.Current.CancellationToken);
        completed.StatusCode.Should().Be(HttpStatusCode.Redirect, "the code was right, so this is setup rather than what the test verifies");
        (await IsRememberedAsync(client)).Should().BeTrue("the browser asked to be remembered");

        return client;
    }

    /// <summary>
    /// Whether the two-factor page tells <paramref name="client"/> its browser is remembered, which it
    /// does by offering to forget it. The page must render: the client has to be signed in.
    /// </summary>
    private async Task<bool> IsRememberedAsync(HttpClient client)
    {
        HttpResponseMessage response = await client.GetAsync("/Account/Manage/TwoFactorAuthentication", TestContext.Current.CancellationToken);
        response.StatusCode.Should().Be(HttpStatusCode.OK, "the two-factor page is read signed in");

        string page = await response.Content.ReadAsStringAsync(TestContext.Current.CancellationToken);
        string forget;

        using (IServiceScope scope = _factory.Services.CreateScope())
        {
            forget = scope.ServiceProvider.GetRequiredService<IStringLocalizer<SharedResource>>()["TwoFactor_ForgetBrowser"].Value;
        }

        return page.Contains(_factory.Services.GetRequiredService<HtmlEncoder>().Encode(forget), StringComparison.Ordinal);
    }

    /// <summary>The link the email page mails to confirm the seeded user's move to <paramref name="newEmail"/>.</summary>
    private async Task<string> ConfirmEmailChangeUrlAsync(string newEmail)
    {
        using IServiceScope scope = _factory.Services.CreateScope();
        UserManager<HSUser> users = scope.ServiceProvider.GetRequiredService<UserManager<HSUser>>();
        HSUser user = await users.FindByEmailAsync(Email) ??
                      throw new InvalidOperationException($"No user seeded for {Email}.");

        string code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(await users.GenerateChangeEmailTokenAsync(user, newEmail)));

        return $"/Account/ConfirmEmailChange?userUuid={user.Uuid}&email={Uri.EscapeDataString(newEmail)}&code={code}";
    }
}
