using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Homespool.Model.Entities;

/// <summary>
/// A pending USB-key enrollment: a token pre-generated by a signed-in user and written to the
/// printer's <c>prusa_printer_settings.ini</c> before the printer has ever made contact. The owner is
/// authenticated by physical possession of the USB stick, which sidesteps the code/claim handshake
/// (AGENT-NOTES protocol-reference §"The .ini path is a second enrollment channel").
/// </summary>
/// <remarks>
/// <para>
/// The <see cref="Printer"/> row already exists at provisioning time — hence <see cref="PrinterId"/>
/// is non-null from the start, unlike a code-exchange <see cref="PrusaConnectRegistration"/> whose
/// printer is created later at claim time.
/// </para>
/// <para>
/// A row exists only while the token is <em>unbound</em>. On the printer's first authenticated request
/// the handler verifies the presented token against these rows, then promotes the match into
/// <see cref="PrusaConnectAuthenticationData"/> and <b>deletes this row</b> — so a provisioned printer,
/// once enrolled, authenticates through the same single fingerprint lookup as every other printer,
/// and the mere presence of a row here means "not yet enrolled" without needing a status flag.
/// </para>
/// </remarks>
public class PrusaConnectProvisioning
{
    public long Id { get; set; }

    /// <summary>The printer this token provisions. Created up front, so never null.</summary>
    public int PrinterId { get; set; }

    [ForeignKey(nameof(PrinterId))]
    public virtual Printer? Printer { get; set; }

    /// <summary>Hash of the pre-provisioned token. The plaintext is shown once and never stored.</summary>
    public required string HashedToken { get; set; }

    public DateTimeOffset CreatedAt { get; set; }
}
